tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

brew "curl"
brew "fish"
brew "git"
brew "mariadb"
brew "mas"

cask "adobe-creative-cloud"
cask 'docker'
cask "figma"
cask "firefox"
cask "google-chrome"
cask "gyazo"
cask "microsoft-edge"
cask "slack"
cask "sourcetree"
cask "visual-studio-code"
cask "zoom"