tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "anyenv"
brew "composer"
brew "curl"
brew "git"
brew "grep"
brew "mariadb"
brew "mas"
brew "mkcert"
brew "nginx"
brew "nss"
brew "pnpm"
brew "starship"
brew "vim"
brew "wget"
brew "yarn"
brew "zsh"

cask "adobe-creative-cloud"
cask "cyberduck"
cask "firefox"
cask "google-chrome"
cask "gyazo"
cask "microsoft-edge"
cask "microsoft-office"
cask "slack"
cask "sourcetree"
cask "visual-studio-code"
cask "zoom"

cask "font-hackgen-nerd"