#!/bin/bash

DOTPATH="$HOME/.dotfiles"
BACKUPPATH="$HOME/.dotfiles-backup"
COLOR_GRAY="\033[1;38;5;243m"
COLOR_BLUE="\033[1;34m"
COLOR_GREEN="\033[1;32m"
COLOR_RED="\033[1;31m"
COLOR_PURPLE="\033[1;35m"
COLOR_YELLOW="\033[1;33m"
COLOR_NONE="\033[0m"

greeting() {
  echo -e "Hello, ${COLOR_BLUE}dotfiles${COLOR_NONE}."
}

has() {
  type "$1" > /dev/null 2>&1
}

error() {
  echo -e "${COLOR_RED}Error: ${COLOR_NONE}$1"
  exit 1
}

init() {
  cd ${DOTPATH}
  if ! has "brew"; then
    /bin/bash -c \
      "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
  brew doctor
  brew update
  brew upgrade
  brew bundle
  brew cleanup
  exec $SHELL -l
  anyenv init
  anyenv install --force-init
  exec $SHELL -l
  mkdir -p $(anyenv root)/plugins
  git clone https://github.com/znz/anyenv-update.git $(anyenv root)/plugins/anyenv-update
  anyenv install nodenv
  exec $SHELL -l
  nodenv install 16.14.2
  nodenv global 16.14.2
}

install() {
  cd ${DOTPATH}
  if [ ! -d ${BACKUPPATH} ]; then
    mkdir -p "$BACKUPPATH"
  fi
  for f in $DOTPATH/.??*; do
    [[ `basename $f` == ".DS_Store" ]] && continue
    [[ `basename $f` == ".git" ]] && continue
    [[ `basename $f` == ".gitignore" ]] && continue
    [[ `basename $f` == ".gitmodules" ]] && continue
    [[ `basename $f` == ".github" ]] && continue
    if [[ -L "$HOME/`basename $f`" ]]; then
      rm -f "$HOME/`basename $f`"
    fi
    if [[ -e "$HOME/`basename $f`" ]]; then
      mv "$HOME/`basename $f`" "$BACKUPPATH"
    fi
    ln -sfnv $f $HOME
  done
  chmod -R 755 "${DOTPATH}/.bin"
}

update() {
  cd ${DOTPATH}
  git pull origin main
}

case "$1" in
  version)
    greeting
    echo -e "`basename $0` version 1.0.0"
    ;;
  init)
    greeting
    echo -e "Start to setup Homebrew and install packages..."
    init
    ;;
  install)
    greeting
    echo -e "Start to remove dotfiles in home directory..."
    install
    ;;
  update)
    greeting
    echo -e "Start to update dotfiles..."
    update
    install
    ;;
  *)
    echo -e "Usage: `basename $0` <command>"
    echo -e "   version       Show version"
    echo -e "   init          Setup Homebrew and install packages"
    echo -e "   install       Install dotfiles to home directory"
    echo -e "   update        Update dotfiles and this repo"
    ;;
esac