# CI

name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  # Test
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dotfiles
        run: sh -c "$(wget -qO- get.chezmoi.io)" -- init --apply -S .
